# Generated by Django 5.1.2 on 2024-11-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0001_initial"),
        ("settings", "0004_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="modified_at",
        ),
        migrations.AddField(
            model_name="segment",
            name="logic",
            field=models.CharField(
                choices=[("EQ", "=="), ("NOTEQ", "!=")], default="==", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="status_value",
            field=models.ManyToManyField(related_name="status", to="settings.status"),
        ),
        migrations.AddField(
            model_name="segment",
            name="tag_value",
            field=models.ManyToManyField(related_name="tags", to="settings.tag"),
        ),
        migrations.AddField(
            model_name="segment",
            name="type",
            field=models.CharField(
                choices=[("STATUS", "status"), ("TAGS", "tags")],
                default="STATUS",
                max_length=20,
            ),
        ),
    ]
