# Generated by Django 5.1.2 on 2024-11-27 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0005_remove_segment_additional_rules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="updated_at",
        ),
    ]
