# Generated by Django 5.1.2 on 2024-11-27 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0007_segment_created_at_alter_segment_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="created_by",
        ),
    ]
