# Generated by Django 5.1.2 on 2024-11-27 21:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0008_alter_contactdetail_tags"),
        ("segments", "0009_remove_segment_conditions_remove_segment_contacts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="conditions",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segment",
            name="contacts",
            field=models.ManyToManyField(
                blank=True, related_name="segments", to="contacts.contactdetail"
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 11, 27, 21, 33, 3, 974237, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segment",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segments_created",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="segment",
            name="type",
            field=models.CharField(
                choices=[("STATUS", "status"), ("TAGS", "tags")],
                default="STATUS",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="value",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
