# Generated by Django 5.1.2 on 2024-11-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0010_segment_conditions_segment_contacts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segment",
            name="logic",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="type",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="value",
        ),
        migrations.AddField(
            model_name="segment",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
