# Generated by Django 5.1.2 on 2024-12-06 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0011_remove_segment_logic_remove_segment_operator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="segments_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
