# Generated by Django 5.1.2 on 2024-11-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_traficksource"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
