# Generated by Django 5.1.2 on 2024-12-06 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0009_remove_contactdetail_trafick_source_and_more"),
        ("settings", "0004_tag"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrafickSource",
            new_name="TrafficSource",
        ),
    ]
