# Generated by Django 5.1.2 on 2024-12-15 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0005_rename_traficksource_trafficsource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name_plural": "Statuses"},
        ),
    ]
