# Generated by Django 5.1.4 on 2025-02-26 05:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0025_contact_company_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=225)),
                ("account_number", models.CharField(max_length=225)),
                ("bank_name", models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("telephone_number", models.CharField(max_length=20)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "business_logo_url",
                    models.URLField(
                        blank=True,
                        default="https://g-linelogistics.com/wp-content/uploads/2023/03/Asset-2.png",
                        null=True,
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "facebook_page",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "linkedin_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Business Setting",
                "verbose_name_plural": "Business Settings",
            },
        ),
        migrations.CreateModel(
            name="InvoiceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#000000", max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        choices=[("₦", "NGN"), ("$", "USD"), ("¥", "Yuan")],
                        default="NGN",
                        max_length=10,
                    ),
                ),
                (
                    "target_currency",
                    models.CharField(
                        choices=[("₦", "NGN"), ("$", "USD"), ("¥", "Yuan")],
                        max_length=10,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "unique_together": {("base_currency", "target_currency")},
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("invoice_date", models.DateField(auto_now_add=True, db_index=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "unit_measurement",
                    models.CharField(
                        choices=[
                            ("Quantity", "Quantity"),
                            ("kg", "Weight (kg)"),
                            ("CBM", "Volume (CBM)"),
                            ("40ft Container", "Container"),
                            ("20ft Container", "Container"),
                        ],
                        default="Quantity",
                        max_length=20,
                    ),
                ),
                (
                    "quote_currency",
                    models.CharField(
                        choices=[("₦", "NGN"), ("$", "USD"), ("¥", "Yuan")],
                        default="NGN",
                        max_length=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Proforma Invoice", "Proforma Invoice"),
                            ("Final Invoice", "Final Invoice"),
                            ("Paid", "Paid"),
                            ("Overdue", "Overdue"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="contacts.contact",
                    ),
                ),
                (
                    "business_settings",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="invoice.businesssettings",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="invoices", to="invoice.invoicetag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "unit_measurement",
                    models.CharField(
                        choices=[
                            ("Quantity", "Quantity"),
                            ("kg", "Weight (kg)"),
                            ("CBM", "Volume (CBM)"),
                            ("40ft Container", "Container"),
                            ("20ft Container", "Container"),
                        ],
                        default="Quantity",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("NGN", "NGN"), ("USD", "USD"), ("Yuan", "Yuan")],
                        default="NGN",
                        max_length=10,
                    ),
                ),
                (
                    "quote_currency_equivalent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoice.invoice",
                    ),
                ),
            ],
        ),
    ]
