# Generated by Django 5.1.4 on 2025-02-23 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0024_remove_contact_dirve_link_contact_drive_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#000000", max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("website_link", models.URLField(blank=True, null=True)),
                ("company_logo_url", models.URLField(blank=True, null=True)),
                (
                    "unit_measurement",
                    models.CharField(
                        choices=[
                            ("Quantity", "Quantity"),
                            ("CBM", "Volume (CBM)"),
                            ("kg", "Weight (kg)"),
                        ],
                        default="Quantity",
                        max_length=20,
                    ),
                ),
                (
                    "quote_currency",
                    models.CharField(
                        choices=[("NGN", "NGN"), ("USD", "USD"), ("Yuan", "Yuan")],
                        default="NGN",
                        max_length=10,
                    ),
                ),
                (
                    "rate_naira_usd",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                (
                    "rate_yuan_usd",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                (
                    "rate_naira_yuan",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "total_vat",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Assign_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="contacts.contact",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="invoice.invoicestatus",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="invoices", to="invoice.invoicetag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "unit_measurement",
                    models.CharField(
                        choices=[
                            ("Quantity", "Quantity"),
                            ("CBM", "Volume (CBM)"),
                            ("kg", "Weight (kg)"),
                        ],
                        default="Quantity",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("NGN", "NGN"), ("USD", "USD"), ("Yuan", "Yuan")],
                        default="NGN",
                        max_length=10,
                    ),
                ),
                (
                    "quote_currency_equivalent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoice.invoice",
                    ),
                ),
            ],
        ),
    ]
