# Generated by Django 5.1.4 on 2025-02-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Proforma Invoice", "Proforma Invoice"),
                    ("Final Invoice", "Final Invoice"),
                    ("Paid", "Paid"),
                    ("Overdue", "Overdue"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="quote_currency",
            field=models.CharField(
                choices=[("₦", "NGN"), ("$", "USD"), ("¥", "Yuan")],
                default="NGN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="unit_measurement",
            field=models.CharField(
                choices=[
                    ("Quantity", "Quantity"),
                    ("kg", "Weight (kg)"),
                    ("CBM", "Volume (CBM)"),
                    ("40ft Container", "Container"),
                    ("20ft Container", "Container"),
                ],
                default="Quantity",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_measurement",
            field=models.CharField(
                choices=[
                    ("Quantity", "Quantity"),
                    ("kg", "Weight (kg)"),
                    ("CBM", "Volume (CBM)"),
                    ("40ft Container", "40ft Container"),
                    ("20ft Container", "20ft Container"),
                ],
                default="Quantity",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="InvoiceStatus",
        ),
    ]
