# Generated by Django 5.1.4 on 2025-02-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0003_invoice_due_date_invoice_invoice_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="company_logo_url",
            new_name="business_logo_url",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="company_name",
            new_name="business_name",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="website_link",
            new_name="website_url",
        ),
        migrations.AddField(
            model_name="invoice",
            name="facebook_page",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="linkedin_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="telephone_number",
            field=models.CharField(default="2348061904041", max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="twitter_handle",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
