# Generated by Django 5.1.4 on 2025-02-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0004_rename_company_logo_url_invoice_business_logo_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoicesettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("telephone_number", models.CharField(max_length=20)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "business_logo_url",
                    models.URLField(
                        blank=True,
                        default="https://g-linelogistics.com/wp-content/uploads/2023/03/Asset-2.png",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="business_logo_url",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="business_name",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="business_type",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="telephone_number",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="website_url",
        ),
    ]
