# Generated by Django 5.1.4 on 2025-02-25 09:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0005_invoicesettings_remove_invoice_business_logo_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=225)),
                ("account_number", models.CharField(max_length=225)),
                ("bank_name", models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("telephone_number", models.CharField(max_length=20)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "business_logo_url",
                    models.URLField(
                        blank=True,
                        default="https://g-linelogistics.com/wp-content/uploads/2023/03/Asset-2.png",
                        null=True,
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "facebook_page",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "linkedin_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Business Setting",
                "verbose_name_plural": "Business Settings",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        choices=[("₦", "NGN"), ("$", "USD"), ("¥", "Yuan")],
                        default="NGN",
                        max_length=10,
                    ),
                ),
                (
                    "target_currency",
                    models.CharField(
                        choices=[("₦", "NGN"), ("$", "USD"), ("¥", "Yuan")],
                        max_length=10,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("base_currency", "target_currency")},
            },
        ),
        migrations.DeleteModel(
            name="Invoicesettings",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="facebook_page",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="linkedin_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="rate_naira_usd",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="rate_naira_yuan",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="rate_yuan_usd",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="twitter_handle",
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                max_length=20,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Proforma Invoice", "Proforma Invoice"),
                    ("Final Invoice", "Final Invoice"),
                    ("Paid", "Paid"),
                    ("Overdue", "Overdue"),
                ],
                db_index=True,
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_vat",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="tax_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_measurement",
            field=models.CharField(
                choices=[
                    ("Quantity", "Quantity"),
                    ("kg", "Weight (kg)"),
                    ("CBM", "Volume (CBM)"),
                    ("40ft Container", "Container"),
                    ("20ft Container", "Container"),
                ],
                default="Quantity",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="business_settings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="invoice.businesssettings",
            ),
        ),
    ]
