# Generated by Django 5.1.2 on 2024-11-02 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdetail",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.status",
            ),
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
