# Generated by Django 5.1.2 on 2024-11-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_address_contactdetail_close_date_and_more"),
        ("settings", "0003_traficksource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactdetail",
            name="traffic_source",
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="trafick_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.traficksource",
            ),
        ),
    ]
