# Generated by Django 5.1.2 on 2024-11-09 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_remove_contactdetail_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactdetail",
            name="address_city",
        ),
        migrations.RemoveField(
            model_name="contactdetail",
            name="address_country",
        ),
        migrations.RemoveField(
            model_name="contactdetail",
            name="address_first_line",
        ),
        migrations.RemoveField(
            model_name="contactdetail",
            name="address_postal_code",
        ),
        migrations.RemoveField(
            model_name="contactdetail",
            name="address_second_line",
        ),
    ]
