# Generated by Django 5.1.2 on 2024-11-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0007_remove_contactdetail_tags_alter_log_created_by_and_more"),
        ("settings", "0004_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdetail",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="contact", to="settings.tag"
            ),
        ),
    ]
