# Generated by Django 5.1.2 on 2024-12-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0008_alter_contactdetail_tags"),
        ("settings", "0004_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactdetail",
            name="trafick_source",
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="traffic_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trafick_source_contact",
                to="settings.traficksource",
            ),
        ),
    ]
