# Generated by Django 5.1.2 on 2024-12-06 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0009_remove_contactdetail_trafick_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactdetail",
            old_name="open_date",
            new_name="date_of_birth",
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="referred_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referee_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
