# Generated by Django 5.1.2 on 2024-12-14 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0010_rename_open_date_contactdetail_date_of_birth_and_more"),
        ("settings", "0005_rename_traficksource_trafficsource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdetail",
            name="services",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="settings.service",
            ),
        ),
        migrations.AlterField(
            model_name="contactdetail",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="settings.status",
            ),
        ),
        migrations.AlterField(
            model_name="contactdetail",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="contacts", to="settings.tag"
            ),
        ),
        migrations.AlterField(
            model_name="contactdetail",
            name="traffic_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="traffic_source_contact",
                to="settings.trafficsource",
            ),
        ),
        migrations.AlterField(
            model_name="contactdetail",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="log_type",
            field=models.CharField(
                choices=[("email", "Email"), ("feedback", "Feedback")], max_length=20
            ),
        ),
    ]
