# Generated by Django 5.1.2 on 2024-12-15 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0011_alter_contactdetail_services_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_line",
                    models.CharField(help_text="Primary address line", max_length=255),
                ),
                (
                    "second_line",
                    models.CharField(
                        blank=True,
                        help_text="Secondary address line (optional)",
                        max_length=255,
                    ),
                ),
                ("city", models.CharField(help_text="City or town", max_length=100)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State or province (if applicable)",
                        max_length=100,
                    ),
                ),
                ("country", models.CharField(help_text="Country", max_length=50)),
                (
                    "postal_code",
                    models.CharField(help_text="Postal or zip code", max_length=20),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="contact_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("On Demand", "On Demand"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="custom_field_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="gdpr_compliant",
            field=models.BooleanField(
                default=False, help_text="Is this contact GDPR compliant?"
            ),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("U", "Prefer not to say"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Widowed", "Widowed"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="marketing_consent",
            field=models.BooleanField(
                default=False,
                help_text="Has this contact consented to marketing communications?",
            ),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Text", "Text"),
                    ("Mail", "Mail"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to="contacts.address",
            ),
        ),
    ]
