# Generated by Django 5.1.4 on 2024-12-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0012_address_contactdetail_contact_frequency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactdetail",
            name="address",
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="address_line1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="contactdetail",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
