# Generated by Django 5.1.4 on 2024-12-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0013_remove_contactdetail_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdetail",
            name="new_or_old",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("On Demand", "On Demand"),
                ],
                max_length=20,
            ),
        ),
    ]
