# Generated by Django 5.1.4 on 2024-12-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0014_contactdetail_new_or_old"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.AlterField(
            model_name="contactdetail",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="contactdetail",
            name="new_or_old",
            field=models.CharField(
                blank=True, choices=[("New", "New"), ("Old", "Old")], max_length=20
            ),
        ),
    ]
