# Generated by Django 5.1.4 on 2025-01-03 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0019_log_updated_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="updated_by",
            new_name="logged_by",
        ),
    ]
