# Generated by Django 5.1.4 on 2025-01-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0020_rename_updated_by_log_logged_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
