# Generated by Django 5.1.4 on 2025-01-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0021_alter_contact_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
