# Generated by Django 5.1.4 on 2025-02-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0022_alter_contact_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="dirve_link",
            field=models.URLField(
                blank=True,
                help_text="URL to the customer's Google Drive folder",
                max_length=500,
                null=True,
            ),
        ),
    ]
