# Generated by Django 5.1.4 on 2025-02-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0023_contact_dirve_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="dirve_link",
        ),
        migrations.AddField(
            model_name="contact",
            name="drive_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
