# Generated by Django 5.1.4 on 2025-02-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0024_remove_contact_dirve_link_contact_drive_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="company_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
