# Generated by Django 5.1.4 on 2025-03-10 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0025_contact_company_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="send_to",
            field=models.ManyToManyField(
                blank=True, related_name="sent_logs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="log_type",
            field=models.CharField(
                choices=[("instruction", "Instruction"), ("feedback", "Feedback")],
                max_length=20,
            ),
        ),
    ]
