# Generated by Django 5.1.4 on 2025-03-10 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0026_log_send_to_alter_log_log_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="logged_by",
        ),
    ]
